/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Solicitud;

import WebServices.SolicitudEquipos;
import WebServices.WebServices;
import WebServices.WebServices_Service;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mdeodanes
 */
public class FrmSolicitud2 extends javax.swing.JFrame {

    /**
     * Creates new form frmSolicitud
     */
    WebServices_Service service = new WebServices_Service();
    WebServices Data = service.getWebServicesPort();

    public FrmSolicitud2() {
        initComponents();
        setIconImage(getIconImage());

        this.setLocationRelativeTo(null);

        lblEstadoSolicitud.setVisible(false);
        cbEstadoSolicitud.setVisible(false);
    }

    public Image getIconImage() {
        Image IconImage = Toolkit
                .getDefaultToolkit()
                .getImage(ClassLoader.getSystemResource("img/IconImage.png"));
        return IconImage;
    }

    List<SolicitudEquipos> lSolicitud;
    int Id_Solicitud;
    String Nombre, Apellido, Codigo_Empleado, Correo, Telefono, Cargo, Tipo_Solicitud, Estado_Solicitud, Mensaje, Estado_Asignado;

    boolean nuevo = false, editar = false;
    boolean eliminar = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaMensaje = new javax.swing.JTextArea();
        txtCorreo = new javax.swing.JTextField();
        txtIdSolicitud = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        txtCargo = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lblEstadoSolicitud = new javax.swing.JLabel();
        cbEstadoSolicitud = new javax.swing.JComboBox<>();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Solicitud usuarios");
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Codigo");

        jLabel1.setText("Nombre");

        jLabel8.setText("Tipo de solicitud");

        txtCodigo.setEditable(false);

        btnBuscar.setText("Buscar Solicitud");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtaMensaje.setColumns(20);
        txtaMensaje.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtaMensaje.setRows(5);
        jScrollPane1.setViewportView(txtaMensaje);

        txtCorreo.setEditable(false);

        txtIdSolicitud.setEditable(false);

        jLabel5.setText("Telefono");

        jLabel4.setText("Correo");

        txtTelefono.setEditable(false);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prestamo", "Asignacion", "Consulta", "Retorno" }));
        cbTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbTipo.setLightWeightPopupEnabled(false);

        txtCargo.setEditable(false);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        txtApellido.setEditable(false);

        jLabel6.setText("Cargo");

        jLabel3.setText("Apellido");

        txtNombre.setEditable(false);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblEstadoSolicitud.setText("Estado Solicitud");

        cbEstadoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Aprobado", "Rechazado", "En Proceso", "Finalizado" }));
        cbEstadoSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbEstadoSolicitud.setLightWeightPopupEnabled(false);

        btnCerrar.setText("Close");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(txtIdSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnBuscar))
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(463, 463, 463))
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(332, 332, 332)))
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(lblEstadoSolicitud)
                                .addComponent(cbEstadoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(94, 94, 94)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblEstadoSolicitud))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstadoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      // TODO add your handling code here:

      try {
          if (btnNuevo.getText().equals("Nuevo")) {
              LimpiarTexbox();
              HabilitarTexbox(true);

              lblEstadoSolicitud.setVisible(false);
              cbEstadoSolicitud.setVisible(false);

              txtIdSolicitud.setEditable(false);

              btnNuevo.setText("Guardar");
              btnEditar.setText("Cancelar");
              btnBuscar.setEnabled(false);
              btnEliminar.setEnabled(false);

              nuevo = true;
              editar = false;
          } else {
              Nombre = txtNombre.getText();
              Apellido = txtApellido.getText();
              Codigo_Empleado = txtCodigo.getText();
              Correo = txtCorreo.getText();
              Telefono = txtTelefono.getText();
              Cargo = txtCargo.getText();
              Tipo_Solicitud = cbTipo.getItemAt(cbTipo.getSelectedIndex());
              Mensaje = txtaMensaje.getText();

              if (txtNombre.getText().trim().isEmpty()) {
                  JOptionPane.showMessageDialog(
                          this,
                          "No dejar campos vacios",
                          "Advertencia",
                          JOptionPane.WARNING_MESSAGE
                  );
              } else {
                  if (nuevo) {
                      int r = Data.agregarSolicitudEquipo(
                              Nombre,
                              Apellido,
                              Codigo_Empleado,
                              Correo,
                              Telefono,
                              Cargo,
                              Tipo_Solicitud,
                              Mensaje
                      );

                      if (r == 1) {
                          JOptionPane.showMessageDialog(
                                  null,
                                  "Registrado con exito ID: " + r
                          );

                          LimpiarTexbox();
                          HabilitarTexbox(false);
                      } else {
                          JOptionPane.showMessageDialog(null, "Error. Error de registro");
                      }
                  } else if (editar) {
                      int r = Data.modificarSolicitud(
                              Id_Solicitud,
                              Nombre,
                              Apellido,
                              Codigo_Empleado,
                              Correo,
                              Telefono,
                              Cargo,
                              Tipo_Solicitud,
                              Mensaje
                      );

                      if (r == 1) {
                          JOptionPane.showMessageDialog(null, "Modificado con exito");
                          LimpiarTexbox();
                          HabilitarTexbox(false);
                      } else {
                          JOptionPane.showMessageDialog(null, "Error al modificar");
                      }
                  }
              }
              nuevo = false;
              editar = false;
              HabilitarTexbox(false);
              btnNuevo.setText("Nuevo");
              btnEditar.setText("Editar");
          }
      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnNuevoActionPerformed

  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      // TODO add your handling code here:

      try {
          if (btnEditar.getText().equals("Editar")) {
              HabilitarTexbox(true);
              txtNombre.requestFocus();

              lblEstadoSolicitud.setVisible(false);
              cbEstadoSolicitud.setVisible(false);
              txtIdSolicitud.setEditable(false);
              btnNuevo.setText("Guardar");
              btnEditar.setText("Cancelar");

              btnEliminar.setEnabled(false);

              nuevo = false;
              editar = true;
          } else {
              nuevo = false;
              editar = false;
              HabilitarTexbox(false);
              btnNuevo.setText("Nuevo");
              btnEditar.setText("Editar");
              btnEliminar.setEnabled(true);
          }
      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnEditarActionPerformed

  private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      // TODO add your handling code here:
      try {
          if (!txtIdSolicitud.isEditable()) {
              HabilitarTexbox(true);
              btnBuscar.setEnabled(true);
              return;
          }

          if (txtIdSolicitud.getText().trim().isEmpty()) {
              JOptionPane.showMessageDialog(this, "Campo de busqueda vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);

          } else if (txtIdSolicitud.getText().trim().length() == 0) {
              Id_Solicitud = 0;
          } else {
              Id_Solicitud = Integer.parseInt(txtIdSolicitud.getText());
          }

          Codigo_Empleado = txtCodigo.getText();

          lSolicitud = Data.buscarSolicitud(Id_Solicitud, Codigo_Empleado, Correo, Estado_Asignado);

          if (lSolicitud.isEmpty()) {
              JOptionPane.showMessageDialog(null, "Registro no encontrado");
              return;
          }

          for (int i = 0; i < lSolicitud.size(); i++) {
              txtIdSolicitud.setText(String.valueOf(lSolicitud.get(i).getIdSolicitud()));
              txtNombre.setText(lSolicitud.get(i).getNombre());
              txtApellido.setText(lSolicitud.get(i).getApellido());
              txtCodigo.setText(lSolicitud.get(i).getCodigoEmpleado());
              txtCorreo.setText(lSolicitud.get(i).getCorreo());
              txtTelefono.setText(lSolicitud.get(i).getTelefono());
              txtCargo.setText(lSolicitud.get(i).getCargo());

              Tipo_Solicitud = String.valueOf(lSolicitud.get(i).getTipoSolicitud());
              cbTipo.setSelectedItem(Tipo_Solicitud);

              Estado_Solicitud
                      = String.valueOf(lSolicitud.get(i).getEstadoSolicitud());
              cbEstadoSolicitud.setSelectedItem(Estado_Solicitud);

              txtaMensaje.setText(lSolicitud.get(i).getMensaje());

              lblEstadoSolicitud.setVisible(true);
              cbEstadoSolicitud.setVisible(true);
          }

      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnBuscarActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      // TODO add your handling code here:
      if (txtIdSolicitud.getText().trim().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Sin registros para eliminar");
      } else {
          try {
              int confirmarEliminar = JOptionPane.showConfirmDialog(
                      this,
                      "Estas seguro de eliminar este registro?",
                      "Advertencia",
                      JOptionPane.YES_NO_OPTION
              );
              if (confirmarEliminar == JOptionPane.OK_OPTION) {
                  Id_Solicitud = Integer.parseInt(txtIdSolicitud.getText());
                  int r = Data.eliminarSolicitud(Id_Solicitud);

                  if (r == 1) {
                      JOptionPane.showMessageDialog(null, "Registro eliminado con exito");
                      LimpiarTexbox();
                  } else {
                      JOptionPane.showMessageDialog(null, "Error al eliminar registro");
                  }
              } else {
              }
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, ex.getMessage());
          }
      }
  }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    public void HabilitarTexbox(boolean editar) {
        txtIdSolicitud.setEditable(editar);
        txtNombre.setEditable(editar);
        txtApellido.setEditable(editar);
        txtCodigo.setEditable(editar);
        txtCorreo.setEditable(editar);
        txtTelefono.setEditable(editar);
        txtCargo.setEditable(editar);
        txtaMensaje.setEditable(editar);
        btnBuscar.setEnabled(!editar);
    }

    public void LimpiarTexbox() {
        txtIdSolicitud.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCodigo.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtCargo.setText("");
        txtaMensaje.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger
                    .getLogger(FrmSolicitud2.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger
                    .getLogger(FrmSolicitud2.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger
                    .getLogger(FrmSolicitud2.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                    .getLogger(FrmSolicitud2.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                new FrmSolicitud2().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbEstadoSolicitud;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstadoSolicitud;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdSolicitud;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextArea txtaMensaje;
    // End of variables declaration//GEN-END:variables
}
