/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Empleado;

import WebServices.Empleados;
import WebServices.LCargoEmpleado;
import WebServices.LDepartEmp;
import WebServices.WebServices;
import WebServices.WebServices_Service;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mdeodanes
 */
public class frmEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form frmEmpleado
     */
    public frmEmpleado() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);

        try {

            List<LCargoEmpleado> lCargo;
            lCargo = Data.listarCargoEmpleado();
            cbCargo.removeAllItems();

            for (int i = 0; i < lCargo.size(); i++) {

                cbCargo.addItem(lCargo.get(i).getIdCargoEmpleado() + " - " + lCargo.get(i).getCargo());
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }

        try {

            List<LDepartEmp> lDepartamento;
            lDepartamento = Data.listarDepartEmp();
            cbDepartamento.removeAllItems();

            for (int i = 0; i < lDepartamento.size(); i++) {

                cbDepartamento.addItem(lDepartamento.get(i).getIdDepartmentoEmpleado() + " - " + lDepartamento.get(i).getDepartamento());

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }

    }

    public Image getIconImage() {

        Image IconImage = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/IconImage.png"));
        return IconImage;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        btnBuscar = new javax.swing.JButton();
        txtIdEmpleado = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoEmpleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        cbCargo = new javax.swing.JComboBox<>();
        cbDepartamento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento de empleado");
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setText("ID");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("Cargo");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Fecha");

        chkEstado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        chkEstado.setText("Activo");
        chkEstado.setContentAreaFilled(false);

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtIdEmpleado.setEditable(false);

        txtNombre.setEditable(false);

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusCycleRoot(true);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtApellido.setEditable(false);

        txtCorreo.setEditable(false);

        txtFecha.setEditable(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Estado");

        txtCodigoEmpleado.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Codigo");

        btnCerrar.setText("Close");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Departamento");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(443, 811, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(179, 179, 179))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtFecha)
                                    .addComponent(jLabel11)
                                    .addComponent(cbDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(cbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chkEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(104, 104, 104))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(chkEstado))
                        .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    WebServices_Service service = new WebServices_Service();
    WebServices Data = service.getWebServicesPort();
    Empleados emp;
    //Privilegios priv;
    List<Empleados> lEmpleado;

    int Id_Empleado, IdDepartamentoEmpleado, IdCargoEmpleado;
    String Nombre, Apellido, Codigo_Empleado, Cargo, Correo, Departamento, Equipo_Asignado, Estado;
    boolean nuevo = false, editar = false;

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      // TODO add your handling code here:

      if (txtIdEmpleado.getText().trim().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Sin registros para eliminar");
      } else {
          try {
              int confirmarEliminar = JOptionPane.showConfirmDialog(
                      this,
                      "Estas seguro de eliminar este registro?",
                      "Advertencia",
                      JOptionPane.YES_NO_OPTION
              );
              if (confirmarEliminar == JOptionPane.OK_OPTION) {
                  Id_Empleado = Integer.parseInt(txtIdEmpleado.getText());
                  int r = Data.eliminarEmpleados(Id_Empleado);

                  if (r == 1) {
                      JOptionPane.showMessageDialog(null, "Registro eliminado con exito");
                      LimpiarTexbox();
                  } else {
                      JOptionPane.showMessageDialog(null, "Error al eliminar registro");
                  }
              } else {
              }
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, ex.getMessage());
          }
      }

  }//GEN-LAST:event_btnEliminarActionPerformed

  private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      // TODO add your handling code here:

      try {

          if (!txtIdEmpleado.isEditable()) {
              HabilitarTexbox(true);
              btnBuscar.setEnabled(true);
              btnEliminar.setEnabled(true);
              return;
          }

          if (txtIdEmpleado.getText().trim().isEmpty()) {
              JOptionPane.showMessageDialog(this, "Campo de busqueda vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);

          } else if (txtIdEmpleado.getText().trim().length() == 0) {

              Id_Empleado = 0;

          } else {
              Id_Empleado = Integer.parseInt(txtIdEmpleado.getText());
          }

          Apellido = txtApellido.getText();

          lEmpleado = Data.buscarEmpleado(Id_Empleado, Apellido, Codigo_Empleado, Estado);

          if (lEmpleado.isEmpty()) {
              JOptionPane.showMessageDialog(null, "Registro no encontrado");
              return;
          }

          for (int i = 0; i < lEmpleado.size(); i++) {
              txtIdEmpleado.setText(String.valueOf(lEmpleado.get(i).getIdEmpleado()));
              txtNombre.setText(lEmpleado.get(i).getNombre());
              txtApellido.setText(lEmpleado.get(i).getApellido());
              txtCodigoEmpleado.setText(lEmpleado.get(i).getCodigoEmpleado());
              txtCorreo.setText(lEmpleado.get(i).getCorreo());
              txtFecha.setText(lEmpleado.get(i).getFechaAsignacion());

              if (lEmpleado.get(i).getEstado() == 1) {
                  chkEstado.setSelected(true);
              } else {
                  chkEstado.setSelected(false);
              }

              Cargo = String.valueOf(lEmpleado.get(i).getIdCargoEmpleado()) + " - " + lEmpleado.get(i).getCargo();
              cbCargo.setSelectedItem(Cargo);

              Departamento = String.valueOf(lEmpleado.get(i).getIdDepartamentoEmpleado()) + " - " + lEmpleado.get(i).getDepartamento();
              cbDepartamento.setSelectedItem(Departamento);

          }
      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnBuscarActionPerformed

  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      // TODO add your handling code here:

      try {
          if (btnEditar.getText().equals("Editar")) {
              HabilitarTexbox(true);
              txtNombre.requestFocus();

              btnNuevo.setText("Guardar");
              btnEditar.setText("Cancelar");

              txtFecha.setEditable(false);
              txtIdEmpleado.setEditable(false);
              btnEliminar.setEnabled(false);

              nuevo = false;
              editar = true;

          } else {
              nuevo = false;
              editar = false;
              LimpiarTexbox();
              HabilitarTexbox(false);
              btnNuevo.setText("Nuevo");
              btnEditar.setText("Editar");
              btnEliminar.setEnabled(true);
          }

      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnEditarActionPerformed

  private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      // TODO add your handling code here:
      try {

          if (btnNuevo.getText().equals("Nuevo")) {
              LimpiarTexbox();
              HabilitarTexbox(true);

              btnNuevo.setText("Guardar");
              btnEditar.setText("Cancelar");
              //btnBuscar.setEnabled(false);
              btnEliminar.setEnabled(false);

              txtFecha.setEditable(false);
              txtIdEmpleado.setEditable(false);

              nuevo = true;
              editar = false;
          } else {

              Nombre = txtNombre.getText();
              Apellido = txtApellido.getText();
              Codigo_Empleado = txtCodigoEmpleado.getText();
              Correo = txtCorreo.getText();

              String idCargo = (String) cbCargo.getSelectedItem();
              IdCargoEmpleado = Integer.parseInt(idCargo.split(" - ")[0]);

              String idDepartamento = (String) cbDepartamento.getSelectedItem();
              IdDepartamentoEmpleado = Integer.parseInt(idDepartamento.split(" - ")[0]);

              if (txtCodigoEmpleado.getText().trim().isEmpty()) {
                  JOptionPane.showMessageDialog(this, "No dejar campos vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
              } else {

                  if (nuevo) {
                      int r = Data.agregarEmpleado(Nombre, Apellido, Codigo_Empleado, Correo, IdCargoEmpleado, IdDepartamentoEmpleado, chkEstado.isSelected());

                      if (r > 0) {
                          JOptionPane.showMessageDialog(
                                  null, "Registro con exito");
                          LimpiarTexbox();
                          HabilitarTexbox(false);
                      } else {
                          JOptionPane.showMessageDialog(null, "Error de registro");
                      }

                  } else if (editar) {
                      int r = Data.modificarEmpleado(Id_Empleado, Nombre, Apellido, Codigo_Empleado, Correo, IdCargoEmpleado, IdDepartamentoEmpleado, chkEstado.isSelected());

                      if (r == 1) {
                          JOptionPane.showMessageDialog(null, "Modificado con exito");
                          LimpiarTexbox();
                          HabilitarTexbox(false);
                      } else {
                          JOptionPane.showMessageDialog(null, "Error al modificar");
                      }
                  }
              }
              nuevo = false;
              editar = false;
              HabilitarTexbox(false);
              btnNuevo.setText("Nuevo");
              btnEditar.setText("Editar");

          }

      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger
                    .getLogger(frmEmpleado.class
                            .getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger
                    .getLogger(frmEmpleado.class
                            .getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger
                    .getLogger(frmEmpleado.class
                            .getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                    .getLogger(frmEmpleado.class
                            .getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                //new frmEmpleado().setVisible(true);
            }
        }
        );
    }

    private void HabilitarTexbox(boolean editar) {
        txtIdEmpleado.setEditable(editar);
        txtNombre.setEditable(editar);
        txtApellido.setEditable(editar);
        txtCodigoEmpleado.setEditable(editar);
        txtCorreo.setEditable(editar);
        txtFecha.setEditable(editar);
    }

    private void LimpiarTexbox() {
        txtIdEmpleado.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCodigoEmpleado.setText("");
        txtCorreo.setText("");

        txtFecha.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
