/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.usuario;

import WebServices.Privilegios;
import WebServices.PrivilegiosGT;
import WebServices.Usuarios;
import WebServices.WebServices;
import WebServices.WebServices_Service;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mdeodanes
 */
public class frmUsuario extends javax.swing.JFrame {

    WebServices_Service service = new WebServices_Service();
    WebServices Data = service.getWebServicesPort();
    Usuarios user;
    Privilegios priv;

    List<Usuarios> lUsers;

    int IdUsuario, IdPrivilegio;
    String Nombre, Login, Password, Email, Fecha, Estado, Privilegio;
    boolean nuevo = false, editar = false;
    boolean eliminar = false;

    /**
     * Creates new form frmUsuario
     */
    public frmUsuario() {
        initComponents();
        setIconImage(getIconImage());

        this.setLocationRelativeTo(null);

        try {
            List<PrivilegiosGT> lPriv = Data.privilegios();
            cbPrivilegio.removeAllItems();

            for (int i = 0; i < lPriv.size(); i++) {
                cbPrivilegio.addItem(
                        lPriv.get(i).getIdPrivilegio() + "-" + lPriv.get(i).getPrivilegio()
                );
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    public Image getIconImage() {

        Image IconImage = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/IconImage.png"));
        return IconImage;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtIdUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cbPrivilegio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento usuarios");
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtIdUsuario.setEditable(false);

        txtNombre.setEditable(false);

        jLabel1.setText("Username");

        txtFecha.setEditable(false);

        jLabel2.setText("Nombre");

        jLabel5.setText("Correo");

        jLabel6.setText("Fecha");

        txtLogin.setEditable(false);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);

        cbPrivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Privilegio");

        jLabel7.setText("Estado");

        chkEstado.setText("Activo");
        chkEstado.setContentAreaFilled(false);

        jLabel8.setText("ID");

        txtPassword.setEditable(false);

        jLabel9.setText("Password");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Close");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)
                        .addGap(47, 47, 47)
                        .addComponent(chkEstado))
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(txtEmail)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(164, 164, 164)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPrivilegio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(57, 57, 57)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(171, 171, 171))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtNombre))
                .addGap(24, 24, 24)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtEmail))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPrivilegio)))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      // TODO add your handling code here:

      try {
          if (!txtIdUsuario.isEditable()) {
              HabilitarTexbox(true);
              btnBuscar.setEnabled(true);
              return;
          }

          if (txtIdUsuario.getText().trim().isEmpty()) {

              JOptionPane.showMessageDialog(this, "Campo de busqueda vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);

          } else if (txtIdUsuario.getText().trim().length() == 0) {
              IdUsuario = 0;
          } else {
              IdUsuario = Integer.parseInt(txtIdUsuario.getText());
          }

          Nombre = txtNombre.getText();
          Login = txtLogin.getText();
          Email = txtEmail.getText();

          String valorCB = (String) cbPrivilegio.getSelectedItem();
          IdPrivilegio = Integer.parseInt(valorCB.split("-")[0]);

          lUsers = Data.buscarUsuario(
                  IdUsuario,
                  Nombre,
                  Login,
                  Email,
                  Estado,
                  IdPrivilegio
          );

          if (lUsers.isEmpty()) {
              JOptionPane.showMessageDialog(null, "Registro no encontrado");
              return;
          }

          for (int i = 0; i < lUsers.size(); i++) {
              txtIdUsuario.setText(String.valueOf(lUsers.get(i).getIdUsuario()));
              txtNombre.setText(lUsers.get(i).getNombre());
              txtLogin.setText(lUsers.get(i).getLogin());
              txtPassword.setText(lUsers.get(i).getPassword());
              txtEmail.setText(lUsers.get(i).getEmail());

              if (lUsers.get(i).getEstado() == 1) {
                  chkEstado.setSelected(true);
              } else {
                  chkEstado.setSelected(false);
              }

              Privilegio = String.valueOf(lUsers.get(i).getIdPrivilegio()) + "-" + lUsers.get(i).getPrivilegio();

              cbPrivilegio.setSelectedItem(Privilegio);

              txtFecha.setText(lUsers.get(i).getFecha());
          }

      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnBuscarActionPerformed

  private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      // TODO add your handling code here:

      try {
          if (btnNuevo.getText().equals("Nuevo")) {
              LimpiarTexbox();
              HabilitarTexbox(true);

              txtFecha.setEditable(false);
              txtIdUsuario.setEditable(false);

              btnNuevo.setText("Guardar");
              btnEditar.setText("Cancelar");
              btnEliminar.setEnabled(false);

              nuevo = true;
              editar = false;
          } else {
              Nombre = txtNombre.getText();
              Login = txtLogin.getText();
              Email = txtEmail.getText();
              Password = txtPassword.getText();

              String valorCB = (String) cbPrivilegio.getSelectedItem();
              IdPrivilegio = Integer.parseInt(valorCB.split("-")[0]);

              if ((txtNombre.getText().trim().isEmpty())
                      || (txtLogin.getText().trim().isEmpty())
                      || (txtEmail.getText().trim().isEmpty())
                      || (txtPassword.getText().trim().isEmpty())) {
                  JOptionPane.showMessageDialog(
                          this,
                          "No dejar campos vacios", "Advertencia", JOptionPane.WARNING_MESSAGE
                  );
                  HabilitarTexbox(true);
              } else {
                  if (nuevo) {
                      int res = Data.agregarUsuario(
                              Nombre,
                              Login,
                              Password,
                              Email,
                              chkEstado.isSelected(),
                              IdPrivilegio
                      );

                      if (res >0) {
                          JOptionPane.showMessageDialog(
                                  null,
                                  "Registrado con exito"
                          );
                          LimpiarTexbox();
                          HabilitarTexbox(false);
                      } else {
                          JOptionPane.showMessageDialog(null, "Error de registro");
                      }
                  } else if (editar) {
                      int res = Data.modificarUsuario(
                              IdUsuario,
                              Nombre,
                              Login,
                              Password,
                              Email,
                              chkEstado.isSelected(),
                              IdPrivilegio
                      );
                      if (res == 1) {
                          JOptionPane.showMessageDialog(null, "Modificado con exito");
                          LimpiarTexbox();
                          HabilitarTexbox(false);
                      } else {
                          JOptionPane.showMessageDialog(null, "Error al modificar");
                      }
                  }
              }
              nuevo = false;
              editar = false;
              HabilitarTexbox(false);
              btnNuevo.setText("Nuevo");
              btnEditar.setText("Editar");
          }
      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnNuevoActionPerformed

  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      // TODO add your handling code here:
      try {
          if (btnEditar.getText().equals("Editar")) {
              HabilitarTexbox(true);
              txtIdUsuario.requestFocus();

              btnNuevo.setText("Guardar");
              btnEditar.setText("Cancelar");
              txtIdUsuario.setEditable(false);
              btnEliminar.setEnabled(false);
              txtFecha.setEditable(false);

              nuevo = false;
              editar = true;
          } else {
              nuevo = false;
              editar = false;
              LimpiarTexbox();
              HabilitarTexbox(false);
              btnNuevo.setText("Nuevo");
              btnEditar.setText("Editar");
              btnEliminar.setEnabled(true);
          }
      } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
  }//GEN-LAST:event_btnEditarActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      // TODO add your handling code here:

      try {
          if (txtIdUsuario.getText().trim().isEmpty()) {
              JOptionPane.showMessageDialog(this, "Sin registros para eliminar");
          } else {
              try {
                  int confirmarEliminar = JOptionPane.showConfirmDialog(
                          this,
                          "Estas seguro de eliminar este registro?",
                          "Advertencia",
                          JOptionPane.YES_NO_OPTION
                  );
                  if (confirmarEliminar == JOptionPane.OK_OPTION) {
                      IdUsuario = Integer.parseInt(txtIdUsuario.getText());
                      int r = Data.eliminarUsuario(IdUsuario);

                      if (r == 1) {
                          JOptionPane.showMessageDialog(
                                  null,
                                  "Registro eliminado con exito"
                          );
                          LimpiarTexbox();
                      } else {
                          JOptionPane.showMessageDialog(null, "Error al eliminar registro");
                      }
                  } else {
                  }
              } catch (Exception ex) {
                  JOptionPane.showMessageDialog(null, ex.getMessage());
              }
          }
      } catch (Exception ex) {
      }
  }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger
                    .getLogger(frmUsuario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger
                    .getLogger(frmUsuario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger
                    .getLogger(frmUsuario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                    .getLogger(frmUsuario.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                new frmUsuario().setVisible(true);
            }
        }
        );
    }

    private void HabilitarTexbox(boolean editar) {
        txtIdUsuario.setEditable(editar);
        txtNombre.setEditable(editar);
        txtLogin.setEditable(editar);
        txtPassword.setEditable(editar);
        txtEmail.setEditable(editar);
        txtFecha.setEditable(editar);
        btnBuscar.setEnabled(!editar);
    }

    //Metodo para limpiar los texbox y checkbox
    private void LimpiarTexbox() {
        txtIdUsuario.setText("");
        txtNombre.setText("");
        txtLogin.setText("");
        txtPassword.setText("");
        txtEmail.setText("");
        txtFecha.setText("");
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbPrivilegio;
    private javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
