/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.CompraEquipo;

import Views.Proveedor.frmProveedor;
import WebServices.LCompras;
import WebServices.LMarca;
import WebServices.Mproveedores;
import WebServices.TipoEquipoGT;
import WebServices.WebServices;
import WebServices.WebServices_Service;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdeodanes
 */
public class frmCompraEquipo extends javax.swing.JFrame {

    /**
     * Creates new form frmCompraEquipo
     */
    public frmCompraEquipo() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        actualizarRegistroCompra();

        //Tipo de equitpo(categoria)
        try {
            List<TipoEquipoGT> lTipo = Data.tipoEquipo();
            cbCategoria.removeAllItems();

            for (int i = 0; i < lTipo.size(); i++) {
                cbCategoria.addItem(lTipo.get(i).getIdTipoEquipo() + " - " + lTipo.get(i).getEquipo());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        //Proveedores
        MostrarProveedores();

        //marca
        try {
            List<LMarca> lMarca;
            lMarca = Data.listarMarca();
            cbMarca.removeAllItems();

            for (int i = 0; i < lMarca.size(); i++) {

                cbMarca.addItem(lMarca.get(i).getIdMarcaModelo() + " - " + (lMarca.get(i).getMarca()));

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }

    }

    public Image getIconImage() {

        Image IconImage = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/IconImage.png"));
        return IconImage;
    }

    WebServices_Service service = new WebServices_Service();
    WebServices Data = service.getWebServicesPort();

    List<LCompras> listarCompras;

    int Id_Proveedor;
    int IdTipoEquipo;
    int IdMarcaModelo;
    int Cantidad;
    double Precio;
    String Descripcion;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        Panel = new javax.swing.JPanel();
        btnRealizarPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbProveedor = new javax.swing.JComboBox<>();
        txtField = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnNuevoProveedor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaCaracteristicas = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cbMarca = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton2.setText("Actualizar pedidos");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realizar compra");
        setResizable(false);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        btnRealizarPedido.setText("Realizar pedido");
        btnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedidoActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar Proveedor");

        cbProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProveedorMouseClicked(evt);
            }
        });

        txtField.setText("Categoria");

        jLabel2.setText("Cantidad");

        btnNuevoProveedor.setText("Nuevo provedor");
        btnNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProveedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio");

        txtaCaracteristicas.setColumns(20);
        txtaCaracteristicas.setRows(5);
        jScrollPane2.setViewportView(txtaCaracteristicas);

        jLabel6.setText("Caracteristicas");

        jLabel3.setText("Marca");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setRowHeight(25);
        jScrollPane3.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(txtField)
                    .addComponent(cbProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(129, 129, 129))
                    .addComponent(txtCantidad)
                    .addComponent(txtPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addComponent(btnNuevoProveedor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRealizarPedido))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
            .addComponent(jScrollPane3)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveedorActionPerformed
        // TODO add your handling code here:
        frmProveedor iframe = new frmProveedor();
        Panel.setVisible(true);
        //Panel.add(iframeUser);
        iframe.setVisible(true);

    }//GEN-LAST:event_btnNuevoProveedorActionPerformed

    private void btnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidoActionPerformed
        // TODO add your handling code here:
        AgregarCompra();
    }//GEN-LAST:event_btnRealizarPedidoActionPerformed

    private void cbProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProveedorMouseClicked
        // TODO add your handling code here:
        MostrarProveedores();
    }//GEN-LAST:event_cbProveedorMouseClicked

    public void AgregarCompra() {
        try {

            if (txtCantidad.getText().trim().isEmpty() || txtCantidad.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No dejar campos vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);

            } else {

                String idProveedor = (String) cbProveedor.getSelectedItem();
                Id_Proveedor = Integer.parseInt(idProveedor.split(" - ")[0]);

                String idCategoria = (String) cbCategoria.getSelectedItem();
                IdTipoEquipo = Integer.parseInt(idCategoria.split(" - ")[0]);

                String idMarca = (String) cbMarca.getSelectedItem();
                IdMarcaModelo = Integer.parseInt(idMarca.split(" - ")[0]);

                Cantidad = (int) Double.parseDouble(txtCantidad.getText());
                Precio = Double.parseDouble(txtPrecio.getText());

                Descripcion = txtaCaracteristicas.getText();

                int res = Data.agregarCompraEquipo(Id_Proveedor, IdTipoEquipo, IdMarcaModelo, Cantidad, Precio, Descripcion);

                if (res >= 0) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Compra registrada");
                    actualizarRegistroCompra();
                    LimpiarTexbox();
                    /*HabilitarTexbox(false);  */
                } else {
                    JOptionPane.showMessageDialog(null, "Error de registro");
                }

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    public void actualizarRegistroCompra() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Proveedor");
        model.addColumn("Name");
        model.addColumn("Lastname");
        model.addColumn("Mail");
        model.addColumn("Phone");
        model.addColumn("Marca");
        model.addColumn("Model");
        model.addColumn("Type");
        model.addColumn("Price");
        model.addColumn("cant");
        model.addColumn("Purchase");

        try {

            jTable1.setModel(model);
            listarCompras = Data.listarCompras();

            Object[] fila = new Object[12];

            for (int i = 0; i < listarCompras.size(); i++) {

                fila[0] = listarCompras.get(i).getIdCompra();
                fila[1] = listarCompras.get(i).getEmpresa();
                fila[2] = listarCompras.get(i).getNombre();
                fila[3] = listarCompras.get(i).getApellido();
                fila[4] = listarCompras.get(i).getCorreo();
                fila[5] = listarCompras.get(i).getTelefono();
                fila[6] = listarCompras.get(i).getMarca();
                fila[7] = listarCompras.get(i).getModelo();
                fila[8] = listarCompras.get(i).getEquipo();
                fila[9] = listarCompras.get(i).getPrecio() + "$";
                fila[10] = listarCompras.get(i).getCantidad();
                fila[11] = listarCompras.get(i).getFechaCompra();

                model.addRow(fila);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener registros");

        }

    }

    public void MostrarProveedores() {

        try {
            List<Mproveedores> lProv;
            lProv = Data.mostrarProveedores();
            cbProveedor.removeAllItems();

            for (int i = 0; i < lProv.size(); i++) {

                cbProveedor.addItem(lProv.get(i).getIdProveedor() + " - " + (lProv.get(i).getEmpresa()));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }

    }

    public void LimpiarTexbox() {

        txtaCaracteristicas.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCompraEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCompraEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCompraEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCompraEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmCompraEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnNuevoProveedor;
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JLabel txtField;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextArea txtaCaracteristicas;
    // End of variables declaration//GEN-END:variables
}
